title: The Practice Players
description: The Practice Players is a lifestyle blog featuring a daily podcast focused around Sports, Fitness, Sneakers, Family, and Faith
email: "sulaiman@thepracticeplayers.com"
copyright: Copyright &copy; 2020 The Practice Players. All rights reserved.

twitter: "practiceplayers"
instagram: "practiceplayers"
youtube: "UCP_8OkBDprwJzn3pDa2HzxA"
facebook: "practiceplayers"

instagram-highlighted-post: "https://www.instagram.com/p/B92R9NPA6FD/"

permalink: /:categories/:year/:month/:day/:title:output_ext

podcast-title: The Practice Players
podcast-organization: The Practice Players
podcast-description: Daily podcast hosted by Sulaiman Ali focused on Sports, Fitness, Sneakers, Family, and Faith.

plugins: 
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag
