title: The Practice Players
description: The Practice Players is a lifestyle blog featuring a daily podcast focused around Sports, Fitness, Sneakers, Family, and Faith
copyright: Copyright &copy; 2020 The Practice Players. All rights reserved.
baseurl: "/thepracticeplayers"

plugins: 
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag
